//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaiTap6.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel;

    public partial class Employee
    {
        [DisplayName("Employee ID:")]
        public int employeeID { get; set; }
        [DisplayName("First name:")]
        public string employeeFirstName { get; set; }
        [DisplayName("Last name:")]
        public string employeeLastName { get; set; }
        [DisplayName("Gender:")]
        public Nullable<bool> employeeGender { get; set; }
        [DisplayName("Date of birth:")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd-MM-yyyy}")]
        public DateTime employeeDateOfBirth { get; set; }
        [DisplayName("Salary:")]
        public Nullable<decimal> employeeSalary { get; set; }
        [DisplayName("Profile picture:")]
        public string employeeProfilePicture { get; set; }
        [DisplayName("Address:")]
        public string employeeAddress { get; set; }
        public int divisionID { get; set; }
        public HttpPostedFileBase employeeImage { get; set; }
        public virtual Division Division { get; set; }
    }
}
